import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  personOutline,
  personAddOutline,
  lockClosedOutline,
  lockOpenOutline,
  mailOutline,
  eyeOutline,
  eyeOffOutline,
  chevronForwardOutline,
  chevronForward,
  arrowForwardOutline,
  arrowBackOutline,
  searchOutline,
  search,
  homeOutline,
  heartOutline,
  heart,
  restaurantOutline,
  timeOutline,
  speedometerOutline,
  cafeOutline,
  pizzaOutline,
  iceCreamOutline,
  peopleOutline,
  imageOutline,
  cameraOutline,
  addOutline,
  checkmarkOutline,
  createOutline,
  closeOutline,
  trashOutline,
  logOutOutline,
  calendarOutline,
  reorderTwoOutline,
  helpCircleOutline,
  alertCircleOutline,
  cloudUploadOutline,
  gridOutline,
  locationOutline,
  callOutline,
  chatbubbleOutline,
  notificationsOutline,
  shieldOutline,
  logInOutline,
  bookmarkOutline,
  flameOutline,
  skullOutline,
  appsOutline,
  addCircleOutline,
  waterOutline,
  imagesOutline,
  chevronBackOutline,
  basketOutline,
  listOutline,
  fitnessOutline,
  refreshOutline,
  documentTextOutline,
  phonePortraitOutline,
  shareOutline,
  person,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  constructor() {
    // Agregar iconos que se usarán en la aplicación
    addIcons({
      personOutline,
      personAddOutline,
      lockClosedOutline,
      lockOpenOutline,
      mailOutline,
      eyeOutline,
      eyeOffOutline,
      chevronForwardOutline,
      chevronForward,
      arrowForwardOutline,
      arrowBackOutline,
      searchOutline,
      search,
      homeOutline,
      heartOutline,
      heart,
      restaurantOutline,
      timeOutline,
      speedometerOutline,
      cafeOutline,
      pizzaOutline,
      iceCreamOutline,
      peopleOutline,
      imageOutline,
      cameraOutline,
      addOutline,
      checkmarkOutline,
      createOutline,
      closeOutline,
      trashOutline,
      logOutOutline,
      calendarOutline,
      reorderTwoOutline,
      helpCircleOutline,
      alertCircleOutline,
      cloudUploadOutline,
      gridOutline,
      locationOutline,
      callOutline,
      chatbubbleOutline,
      notificationsOutline,
      shieldOutline,
      logInOutline,
      bookmarkOutline,
      flameOutline,
      skullOutline,
      appsOutline,
      addCircleOutline,
      waterOutline,
      imagesOutline,
      chevronBackOutline,
      basketOutline,
      listOutline,
      fitnessOutline,
      refreshOutline,
      documentTextOutline,
      phonePortraitOutline,
      shareOutline,
      person,
    });
  }
}
